### PR TITLE
Issue 6

### LINKED ISSUE #6: error: inline assembly is not stable enough for use and is subject to change
i'm trying to use the ethereum-types crate for benchmarks in paritydb so they don't have to depend on all of parity. specifically i need `H160`. (https://github.com/paritytech/paritydb/issues/45#issuecomment-346655071, https://github.com/paritytech/paritydb/issues/45#issuecomment-347159200)

i've added it to `Cargo.toml` like so:
```
ethereum-types = { git = "https://github.com/paritytech/primitives" }
```

```
$ rustc --version
rustc 1.23.0-nightly (827cb0d61 2017-11-26)
```

when i run `cargo bench` i get `error: Could not compile ethereum-types` with a lot of errors like:
```
error: inline assembly is not stable enough for use and is subject to change (see issue #29722)
 --> /Users/basilisk/.cargo/git/checkouts/primitives-d1f10887bbb6b363/d910e92/ethereum-types/src/uint.rs:2:1
  |                                                             
2 | construct_uint!(U256, 4);                                                                                               
  | ^^^^^^^^^^^^^^^^^^^^^^^^^             
  |                                                                                            
  = help: add #![feature(asm)] to the crate attributes to enable                                            
  = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)
                             
error: inline assembly is not stable enough for use and is subject to change (see issue #29722)
 --> /Users/basilisk/.cargo/git/checkouts/primitives-d1f10887bbb6b363/d910e92/ethereum-types/src/uint.rs:2:1
  |                                                             
2 | construct_uint!(U256, 4);                                                                                               
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
  |                                                                                            
  = help: add #![feature(asm)] to the crate attributes to enable                                            
  = note: this error originates in a macro outside of the current crate (run with -Z external-macro-backtrace for more info)
```

### PR DESCRIPTION
**Pull request by snd**
fixes https://github.com/paritytech/primitives/issues/6

### CODE REVIEW

**Review by tomusdrw — APPROVED** [review]

**Comment by snd** [comment]
making nightly build pass as well. just a sec

**Comment by snd** [comment]
done. ready for merge i guess

**Comment by tomusdrw** [comment]
Why is it needed in tests? Do we generate new types there?
Would it be possible to put the features import inside the macro? - i.e. the library users wouldn't need to do that.

**Comment by snd** [comment]
without also adding it to tests (https://github.com/paritytech/primitives/pull/7/commits/4ffc791a5f47cc9e227dd669488ec3a4aa964bd8) the nightly build fails:
https://travis-ci.org/paritytech/primitives/jobs/311794059#L527

this is because `tests/src/uint_tests.rs` uses the `construct_uint!` macro which uses the `uint_overflowing_add!` macro which uses the `asm!` macro which requires `feature(asm)`.

> Would it be possible to put the features import inside the macro? - i.e. the library users wouldn't need to do that.

good idea. i'll try that.

**Comment by snd** [comment]
> Would it be possible to put the features import inside the macro? - i.e. the library users wouldn't need to do that.

unfortunately `feature` is a crate only attribute and not allowed inside macros

**Comment by tomusdrw** [comment]
ok!

**Comment by snd** [comment]
ah, i had just pushed something which broke it again. i'll open another PR after lunch that will finally fix it

**Pull request merged**
